version: 2
updates:
  # Global
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
  # AWS
  - package-ecosystem: "docker"
    directory: "/aws"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "docker"
      - "aws"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
  # Azure
  - package-ecosystem: "docker"
    directory: "/azure"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "docker"
      - "azure"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
  # Chrome
  - package-ecosystem: "docker"
    directory: "/chrome"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "docker"
      - "chrome"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
  # Cloudsploit
  - package-ecosystem: "docker"
    directory: "/cloudsploit"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "docker"
      - "cloudsploit"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: "npm"
    directory: "/cloudsploit"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "npm"
      - "cloudsploit"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
  # DIND
  - package-ecosystem: "docker"
    directory: "/dind"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "docker"
      - "dind"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: "pip"
    directory: "/dind"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "pip"
      - "dind"
  # Golang
  - package-ecosystem: "docker"
    directory: "/golang/1.24"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "docker"
      - "golang"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
  - package-ecosystem: "docker"
    directory: "/golang/1.25"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "docker"
      - "golang"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]

  # Java
  - package-ecosystem: "docker"
    directory: "/java/17"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "docker"
      - "java"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: "docker"
    directory: "/java/21"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "docker"
      - "java"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
  # Node
  - package-ecosystem: "docker"
    directory: "/node"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "docker"
      - "node"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
  # Php
  - package-ecosystem: "docker"
    directory: "/php/8.1"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "docker"
      - "php"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
  -   package-ecosystem: "docker"
      directory: "/php/8.2"
      schedule:
        interval: "weekly"
      labels:
        - "dependencies"
        - "docker"
        - "php"
      ignore:
        -   dependency-name: "*"
            update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
  -   package-ecosystem: "docker"
      directory: "/php/8.3"
      schedule:
        interval: "weekly"
      labels:
        - "dependencies"
        - "docker"
        - "php"
      ignore:
        -   dependency-name: "*"
            update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
  -   package-ecosystem: "docker"
      directory: "/php/8.4"
      schedule:
        interval: "weekly"
      labels:
        - "dependencies"
        - "docker"
        - "php"
      ignore:
        -   dependency-name: "*"
            update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
  # Platformsh
  - package-ecosystem: "docker"
    directory: "/platformsh"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "docker"
      - "platformsh"
  # Python
  - package-ecosystem: "docker"
    directory: "/python/3.9"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "docker"
      - "python"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
  - package-ecosystem: "docker"
    directory: "/python/3.10"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "docker"
      - "python"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
  - package-ecosystem: "docker"
    directory: "/python/3.11"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "docker"
      - "python"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
  - package-ecosystem: "docker"
    directory: "/python/3.12"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "docker"
      - "python"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
  - package-ecosystem: "docker"
    directory: "/python/3.13"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "docker"
      - "python"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
  # Scaleway
  - package-ecosystem: "docker"
    directory: "/scaleway"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "docker"
      - "scaleway"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
  # Sonar
  - package-ecosystem: "docker"
    directory: "/sonar"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "docker"
      - "sonar"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
