versions:
  "7.1":
    platforms:
      - linux/amd64
      - linux/arm64
    build_args:
      SONARSCANNER_VERSION: 7.1.0.4889
    test_config:
      cmd:
        - java -version
        - sonar-scanner -v
