test_config: &test_config
  cmd:
    - node --version
    - npm --version
    - aws --version
    - yarn --version
    - sass --version
    - task --version

versions:
  "20":
    platforms:
      - linux/amd64
      - linux/arm64
    build_args:
      NODE_VERSION: 20.19.1
      NPM_VERSION: 10.9.2
      NVM_VERSION: 0.40.3
    test_config: *test_config
  "22":
    platforms:
      - linux/amd64
      - linux/arm64
    build_args:
      NODE_VERSION: 22.15.0
      NPM_VERSION: 10.9.2
      NVM_VERSION: 0.40.3
    test_config: *test_config
