test_config: &test_config
  cmd:
    - node --version
    - npm --version
    - aws --version
    - yarn --version
    - sass --version
    - task --version

versions:
  "20":
    platforms:
      - linux/amd64
      - linux/arm64
    test_config: *test_config
  "22":
    platforms:
      - linux/amd64
      - linux/arm64
    test_config: *test_config
  "24":
    platforms:
      - linux/amd64
      - linux/arm64
    test_config: *test_config
