platforms: &platforms
  - linux/amd64
  - linux/arm64

test_config: &test_config
  cmd:
    - pip --version
    - python --version
    - aws --version
    - poetry --version

build_args: &build_args
  POETRY_HOME: "/usr/local"

versions:
  "3.9":
    build_args: *build_args
    platforms: *platforms
    test_config: *test_config
  "3.10":
    build_args: *build_args
    platforms: *platforms
    test_config: *test_config
  "3.11":
    build_args: *build_args
    platforms: *platforms
    test_config: *test_config
  "3.12":
    build_args: *build_args
    platforms: *platforms
    test_config: *test_config
  "3.13":
    build_args: *build_args
    platforms: *platforms
    test_config:
      cmd:
        - pip --version
        - python --version
        - aws --version
        - poetry --version
        - psql --version
