versions:
  "1":
    platforms:
      - linux/amd64
      - linux/arm64
    test_config:
      cmd:
        - git --version
        - upsun --version
        - platform --version
        - python --version
        - pip --version
        - pipenv --version