platforms: &platforms
  - linux/amd64
  - linux/arm64

test_config: &test_config
  volume: php:/tmp
  cmd:
    - php --version
    - composer --version
    - php-cs-fixer --version
    - php /tmp/test.php
    - aws --version
build_args: &build_args
  APCU_VERSION: 5.1.26
  COMPOSER_VERSION: 2.8.10
  MEMCACHED_VERSION: 3.3.0
  PHP_CS_FIXER_VERSION: 3.86.0
  REDIS_VERSION: 6.2.0
  XDEBUG_VERSION: 3.4.5
versions:
  "8.1":
    platforms: *platforms
    build_args:
      <<: *build_args
    test_config: *test_config
  "8.2":
    platforms: *platforms
    build_args:
      <<: *build_args
    test_config: *test_config
  "8.3":
    platforms: *platforms
    build_args:
      <<: *build_args
    test_config: *test_config
  "8.4":
    platforms: *platforms
    build_args:
      <<: *build_args
    test_config: *test_config
